name: firebasestoragemanager
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.1.2
  cloud_firestore: ^4.13.6
  equatable: ^2.0.5
  file_selector: ^1.0.1
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_storage: ^11.5.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  gap: ^3.0.1
  intl: ^0.18.1
  intl_translation: ^0.18.2
  mime: ^1.0.4
  pointycastle: ^3.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/svg/

  fonts:
    - family: SocialIcons
      fonts:
        - asset: assets/fonts/SocialIcons.ttf
    - family: Staatliches
      fonts:
        - asset: assets/fonts/Staatliches/Staatliches-Regular.ttf
    - family: NotoSans
      fonts:
        - asset: assets/fonts/Noto_Sans/NotoSans-Italic-VariableFont_wdth,wght.ttf
          style: italic
        - asset: assets/fonts/Noto_Sans/NotoSans-VariableFont_wdth,wght.ttf

